apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-dep
  labels:
    nginx: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        nginx: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
        requests:
          memory: "128Mi"   
          cpu: "250m"       
        limits:
          memory: "256Mi"   
          cpu: "500m" 
        port: 80



  
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  containers:
    - name: nginx 
      image: nginx
  