apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-prod
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      bb: list-products
  template:
    metadata:
      labels:
        bb: list-products
    spec:
      containers:
        - name: store-prod
          image: linuxacademycontent/store-products:1.0.0
          port: 80
--------
apiVersion: apps/v1
kind: Service
metadata:
  name: store-prod
  namespace: default
spec: 
  selector:
    bb: list-products
  ports:
    - protocol: TCP
    - port: 80
    

      